scenario=/home/vimkim/tmp/oos-readiness-221/isolation-debug-clean/scenario/isolation
parallel_slots=1
scenario_disk=on
testcase_timeout_in_secs=300
testcase_retry_num=0
testcase_update_yn=no
test_continue_yn=no
feedback_type=file
backup_core_file_yn=no
