CREATE TABLE t (id INT, v1 BIT VARYING, v2 BIT VARYING);
INSERT INTO t VALUES (1, CAST(REPEAT('AA', 6000) AS BIT VARYING), CAST(REPEAT('BB', 6000) AS BIT VARYING));
SHOW HEAP OOS OF t;
SET SYSTEM PARAMETERS 'fault_injection_ids=700001; fault_injection_fire_at_occurrence=0';
SELECT id, (v1 = CAST(REPEAT('AA', 6000) AS BIT VARYING)) AS eq1, (v2 = CAST(REPEAT('BB', 6000) AS BIT VARYING)) AS eq2 FROM t;
SET SYSTEM PARAMETERS 'fault_injection_ids=1';
SELECT id, (v1 = CAST(REPEAT('AA', 6000) AS BIT VARYING)) AS eq1, (v2 = CAST(REPEAT('BB', 6000) AS BIT VARYING)) AS eq2 FROM t;
