java.runtime.name=OpenJDK Runtime Environment
sun.boot.library.path=/home/vimkim/java/jre/lib/amd64
default.broker2.APPL_SERVER_SHM_ID=13091
java.vm.version=25.462-b08
java.vm.vendor=Temurin
java.vendor.url=https://adoptium.net/
path.separator=:
java.vm.name=OpenJDK 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=US
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
default.broker1.APPL_SERVER_SHM_ID=10090
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/home/vimkim
java.runtime.version=1.8.0_462-b08
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.endorsed.dirs=/home/vimkim/java/jre/lib/endorsed
os.arch=amd64
line.separator=

java.io.tmpdir=/tmp
testcase_retry_num=0
testcase_timeout_in_secs=720
java.vm.specification.vendor=Oracle Corporation
os.name=Linux
sun.jnu.encoding=UTF-8
java.library.path=/home/vimkim/CUBRID/lib:/home/vimkim/CUBRID/cci/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
scenario=/home/vimkim/cubrid-testcases-private-ex/shell/_35_cherry/issue_21654_server_side_loaddb/partition_tbls
java.class.version=52.0
java.specification.name=Java Platform API Specification
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
delete_testcase_after_each_execution_yn=false
os.version=5.14.0-570.30.1.el9_6.x86_64
test_platform=linux
enable_check_disk_space_yn=false
user.home=/root
user.timezone=Asia/Seoul
java.awt.printerjob=sun.print.PSPrinterJob
java.specification.version=1.8
file.encoding=UTF-8
testcase_git_branch=develop
feedback_type=file
default.broker2.BROKER_PORT=13091
user.name=root
java.class.path=/home/vimkim/CTP/common/lib/cubridqa-common.jar
test_continue_yn=false
test_category=shell
java.vm.specification.version=1.8
sun.arch.data.model=64
java.home=/home/vimkim/java/jre
sun.java.command=com.navercorp.cubridqa.ctp.CTP shell -c /home/vimkim/shell.conf
java.specification.vendor=Oracle Corporation
user.language=en
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=mixed mode
java.version=1.8.0_462
java.ext.dirs=/home/vimkim/java/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path=/home/vimkim/java/jre/lib/resources.jar:/home/vimkim/java/jre/lib/rt.jar:/home/vimkim/java/jre/lib/sunrsasign.jar:/home/vimkim/java/jre/lib/jsse.jar:/home/vimkim/java/jre/lib/jce.jar:/home/vimkim/java/jre/lib/charsets.jar:/home/vimkim/java/jre/lib/jfr.jar:/home/vimkim/java/jre/classes
java.vendor=Temurin
java.specification.maintenance.version=6
default.cubrid.cubrid_port_id=1568
file.separator=/
java.vendor.url.bug=https://github.com/adoptium/adoptium-support/issues
testcase_update_yn=false
sun.cpu.endian=little
sun.io.unicode.encoding=UnicodeLittle
sun.rmi.transport.connectionTimeout=10000000
default.broker1.BROKER_PORT=10090
default.ha.ha_port_id=19909
sun.cpu.isalist=
AUTO_TEST_VERSION=11.5.0.2575-ba88e47
AUTO_TEST_BITS=64bits
