CREATE TABLE deferred_base (id INT, data_col BIT VARYING STORAGE FORCE_OUTLINE)
PARTITION BY RANGE (id) (PARTITION p0 VALUES LESS THAN (10), PARTITION p1 VALUES LESS THAN MAXVALUE);
INSERT INTO deferred_base VALUES (1, REPEAT(X'EE', 64));
COMMIT;
SELECT data_col = CAST(REPEAT(X'EE',64) AS BIT VARYING) AS value_matches FROM deferred_base WHERE id=1;
SHOW ALL HEAP OOS OF deferred_base;
