CREATE TABLE small_inline (id INTEGER PRIMARY KEY, value_bits BIT VARYING);
CREATE TABLE large_oos (id INTEGER PRIMARY KEY, value_bits BIT VARYING);
INSERT INTO small_inline VALUES (1, CAST (REPEAT ('AA', 100) AS BIT VARYING));
INSERT INTO large_oos VALUES (1, CAST (REPEAT ('BB', 5000) AS BIT VARYING));
COMMIT;
