[broker]
MASTER_SHM_ID=0x6200002a
ADMIN_LOG_FILE=log/broker/cubrid_broker.log

[%workenv]
SERVICE=ON
BROKER_PORT=41043
APPL_SERVER_SHM_ID=0x6200002b
MIN_NUM_APPL_SERVER=1
MAX_NUM_APPL_SERVER=5
LOG_DIR=log/broker/sql_log
ERROR_LOG_DIR=log/broker/error_log
SQL_LOG=ON
KEEP_CONNECTION=AUTO
CCI_DEFAULT_AUTOCOMMIT=ON
