CREATE TABLE t (id INT, v BIT VARYING);
INSERT INTO t SELECT ROWNUM, CAST(REPEAT('AA', 8000) AS BIT VARYING) FROM db_class a LIMIT 8;
COMMIT;
SHOW HEAP OOS OF t;
UPDATE t SET v = CAST(REPEAT('FA', 8000) AS BIT VARYING);
COMMIT;
SHOW HEAP OOS OF t;
SET SYSTEM PARAMETERS 'fault_injection_ids=700002; fault_injection_fire_at_occurrence=1';
CREATE TABLE IF NOT EXISTS filler (id INT, v BIT VARYING); INSERT INTO filler SELECT ROWNUM, CAST(REPEAT('DD', 12000) AS BIT VARYING) FROM db_class a, db_class b LIMIT 60; COMMIT;
