CREATE TABLE t (id INT, v1 BIT VARYING, v2 BIT VARYING);
SET SYSTEM PARAMETERS 'fault_injection_ids=700005; fault_injection_fire_at_occurrence=2';
INSERT INTO t VALUES (1, CAST(REPEAT('BB', 20000) AS BIT VARYING), CAST(REPEAT('CC', 40000) AS BIT VARYING));
SET SYSTEM PARAMETERS 'fault_injection_ids=1';
SELECT COUNT(*) FROM t;
SHOW HEAP OOS OF t;
INSERT INTO t VALUES (2, CAST(REPEAT('BB', 20000) AS BIT VARYING), CAST(REPEAT('CC', 40000) AS BIT VARYING));
SELECT id, (v1 = CAST(REPEAT('BB', 20000) AS BIT VARYING)) AS eq1, (v2 = CAST(REPEAT('CC', 40000) AS BIT VARYING)) AS eq2 FROM t ORDER BY id;
SHOW HEAP OOS OF t;
