-- pinned engine f4299ac0c, 16K pages, database br16k
-- 1. record gate (schema A: id INT, v BIT VARYING)
CREATE TABLE a_in   (id INT, v BIT VARYING);
CREATE TABLE a_out  (id INT, v BIT VARYING);
CREATE TABLE a_norm (id INT, v BIT VARYING);
INSERT INTO a_in   VALUES (1, CAST(REPEAT('AA', 4035)  AS BIT VARYING));
INSERT INTO a_out  VALUES (1, CAST(REPEAT('BB', 4036) AS BIT VARYING));
INSERT INTO a_norm VALUES (1, CAST(REPEAT('CC', 4012) AS BIT VARYING));
SELECT 'a_in 4035'   AS probe, (v = CAST(REPEAT('AA', 4035)  AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes, DISK_SIZE(v) AS disk_size FROM a_in;
SELECT 'a_out 4036' AS probe, (v = CAST(REPEAT('BB', 4036) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes, DISK_SIZE(v) AS disk_size FROM a_out;
SELECT 'a_norm 4012' AS probe, (v = CAST(REPEAT('CC', 4012) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes, DISK_SIZE(v) AS disk_size FROM a_norm;
SHOW HEAP OOS OF a_in;
SHOW HEAP OOS OF a_out;
SHOW HEAP OOS OF a_norm;
-- 2. single-to-multi chunk boundary
CREATE TABLE c1 (id INT, v BIT VARYING);
CREATE TABLE c2 (id INT, v BIT VARYING);
INSERT INTO c1 VALUES (1, CAST(REPEAT('AB', 16283) AS BIT VARYING));
INSERT INTO c2 VALUES (1, CAST(REPEAT('CD', 16284) AS BIT VARYING));
SELECT 'c1 16283' AS probe, (v = CAST(REPEAT('AB', 16283) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes FROM c1;
SELECT 'c2 16284' AS probe, (v = CAST(REPEAT('CD', 16284) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes FROM c2;
SHOW HEAP OOS OF c1;
SHOW HEAP OOS OF c2;
-- 3. eligibility floor: fixed BIT pushes the record over the gate; s is the only candidate
CREATE TABLE e15 (id INT, f BIT(32688), s BIT VARYING);
CREATE TABLE e16 (id INT, f BIT(32688), s BIT VARYING);
CREATE TABLE e23 (id INT, f BIT(32688), s BIT VARYING);
CREATE TABLE e24 (id INT, f BIT(32688), s BIT VARYING);
INSERT INTO e15 VALUES (1, CAST(REPEAT('AA', 4086) AS BIT(32688)), CAST(REPEAT('D1', 15) AS BIT VARYING));
INSERT INTO e16 VALUES (1, CAST(REPEAT('AA', 4086) AS BIT(32688)), CAST(REPEAT('D2', 16) AS BIT VARYING));
INSERT INTO e23 VALUES (1, CAST(REPEAT('AA', 4086) AS BIT(32688)), CAST(REPEAT('D3', 23) AS BIT VARYING));
INSERT INTO e24 VALUES (1, CAST(REPEAT('AA', 4086) AS BIT(32688)), CAST(REPEAT('D4', 24) AS BIT VARYING));
SHOW HEAP OOS OF e15;
SHOW HEAP OOS OF e16;
SHOW HEAP OOS OF e23;
SHOW HEAP OOS OF e24;
SELECT 'e16' AS probe, (s = CAST(REPEAT('D2', 16) AS BIT VARYING)) AS whole_value_eq FROM e16;
SELECT 'e24' AS probe, (s = CAST(REPEAT('D4', 24) AS BIT VARYING)) AS whole_value_eq FROM e24;
-- 4. OOS + bigone rejection
CREATE TABLE b_ok  (id INT, f BIT(129408),  v BIT VARYING);
CREATE TABLE b_rej (id INT, f BIT(129416), v BIT VARYING);
INSERT INTO b_ok  VALUES (1, CAST(REPEAT('AA', 16176)  AS BIT(129408)),  CAST(REPEAT('EE', 64) AS BIT VARYING));
INSERT INTO b_rej VALUES (1, CAST(REPEAT('AA', 16177) AS BIT(129416)), CAST(REPEAT('EE', 64) AS BIT VARYING));
SELECT 'b_ok rows' AS probe, COUNT(*) FROM b_ok;
SELECT 'b_rej rows' AS probe, COUNT(*) FROM b_rej;
SHOW HEAP OOS OF b_ok;
SHOW HEAP OOS OF b_rej;
-- 5. placement hints present at the pin (syntax only)
CREATE TABLE h (id INT, p BIT VARYING STORAGE PREFER_INLINE, q BIT VARYING STORAGE FORCE_OUTLINE);
INSERT INTO h VALUES (1, CAST(REPEAT('AA', 40) AS BIT VARYING), CAST(REPEAT('BB', 40) AS BIT VARYING));
SHOW HEAP OOS OF h;
