-- pinned engine f4299ac0c, 4K pages, database br4k
-- 1. record gate (schema A: id INT, v BIT VARYING)
CREATE TABLE a_in   (id INT, v BIT VARYING);
CREATE TABLE a_out  (id INT, v BIT VARYING);
CREATE TABLE a_norm (id INT, v BIT VARYING);
INSERT INTO a_in   VALUES (1, CAST(REPEAT('AA', 963)  AS BIT VARYING));
INSERT INTO a_out  VALUES (1, CAST(REPEAT('BB', 964) AS BIT VARYING));
INSERT INTO a_norm VALUES (1, CAST(REPEAT('CC', 940) AS BIT VARYING));
SELECT 'a_in 963'   AS probe, (v = CAST(REPEAT('AA', 963)  AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes, DISK_SIZE(v) AS disk_size FROM a_in;
SELECT 'a_out 964' AS probe, (v = CAST(REPEAT('BB', 964) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes, DISK_SIZE(v) AS disk_size FROM a_out;
SELECT 'a_norm 940' AS probe, (v = CAST(REPEAT('CC', 940) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes, DISK_SIZE(v) AS disk_size FROM a_norm;
SHOW HEAP OOS OF a_in;
SHOW HEAP OOS OF a_out;
SHOW HEAP OOS OF a_norm;
-- 2. single-to-multi chunk boundary
CREATE TABLE c1 (id INT, v BIT VARYING);
CREATE TABLE c2 (id INT, v BIT VARYING);
INSERT INTO c1 VALUES (1, CAST(REPEAT('AB', 3995) AS BIT VARYING));
INSERT INTO c2 VALUES (1, CAST(REPEAT('CD', 3996) AS BIT VARYING));
SELECT 'c1 3995' AS probe, (v = CAST(REPEAT('AB', 3995) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes FROM c1;
SELECT 'c2 3996' AS probe, (v = CAST(REPEAT('CD', 3996) AS BIT VARYING)) AS whole_value_eq, LENGTH(v)/8 AS bytes FROM c2;
SHOW HEAP OOS OF c1;
SHOW HEAP OOS OF c2;
-- 3. eligibility floor: fixed BIT pushes the record over the gate; s is the only candidate
CREATE TABLE e15 (id INT, f BIT(8112), s BIT VARYING);
CREATE TABLE e16 (id INT, f BIT(8112), s BIT VARYING);
CREATE TABLE e23 (id INT, f BIT(8112), s BIT VARYING);
CREATE TABLE e24 (id INT, f BIT(8112), s BIT VARYING);
INSERT INTO e15 VALUES (1, CAST(REPEAT('AA', 1014) AS BIT(8112)), CAST(REPEAT('D1', 15) AS BIT VARYING));
INSERT INTO e16 VALUES (1, CAST(REPEAT('AA', 1014) AS BIT(8112)), CAST(REPEAT('D2', 16) AS BIT VARYING));
INSERT INTO e23 VALUES (1, CAST(REPEAT('AA', 1014) AS BIT(8112)), CAST(REPEAT('D3', 23) AS BIT VARYING));
INSERT INTO e24 VALUES (1, CAST(REPEAT('AA', 1014) AS BIT(8112)), CAST(REPEAT('D4', 24) AS BIT VARYING));
SHOW HEAP OOS OF e15;
SHOW HEAP OOS OF e16;
SHOW HEAP OOS OF e23;
SHOW HEAP OOS OF e24;
SELECT 'e16' AS probe, (s = CAST(REPEAT('D2', 16) AS BIT VARYING)) AS whole_value_eq FROM e16;
SELECT 'e24' AS probe, (s = CAST(REPEAT('D4', 24) AS BIT VARYING)) AS whole_value_eq FROM e24;
-- 4. OOS + bigone rejection
CREATE TABLE b_ok  (id INT, f BIT(31104),  v BIT VARYING);
CREATE TABLE b_rej (id INT, f BIT(31112), v BIT VARYING);
INSERT INTO b_ok  VALUES (1, CAST(REPEAT('AA', 3888)  AS BIT(31104)),  CAST(REPEAT('EE', 64) AS BIT VARYING));
INSERT INTO b_rej VALUES (1, CAST(REPEAT('AA', 3889) AS BIT(31112)), CAST(REPEAT('EE', 64) AS BIT VARYING));
SELECT 'b_ok rows' AS probe, COUNT(*) FROM b_ok;
SELECT 'b_rej rows' AS probe, COUNT(*) FROM b_rej;
SHOW HEAP OOS OF b_ok;
SHOW HEAP OOS OF b_rej;
-- 5. placement hints present at the pin (syntax only)
CREATE TABLE h (id INT, p BIT VARYING STORAGE PREFER_INLINE, q BIT VARYING STORAGE FORCE_OUTLINE);
INSERT INTO h VALUES (1, CAST(REPEAT('AA', 40) AS BIT VARYING), CAST(REPEAT('BB', 40) AS BIT VARYING));
SHOW HEAP OOS OF h;
