CREATE TABLE t (id INT, v BIT VARYING);
SET SYSTEM PARAMETERS 'fault_injection_ids=1; fault_injection_fire_at_occurrence=0';
INSERT INTO t VALUES (1, CAST(REPEAT('AA', 8000) AS BIT VARYING));
SET SYSTEM PARAMETERS 'fault_injection_ids=1';
INSERT INTO t VALUES (2, CAST(REPEAT('AA', 8000) AS BIT VARYING));
SELECT COUNT(*) FROM t; SELECT id, (v = CAST(REPEAT('AA', 8000) AS BIT VARYING)) AS eq8k, (v = CAST(REPEAT('BB', 20000) AS BIT VARYING)) AS eq20k, (v = CAST(REPEAT('CC', 40000) AS BIT VARYING)) AS eq40k FROM t ORDER BY id; SHOW HEAP OOS OF t;
