CREATE TABLE t (id INT, v BIT VARYING);
INSERT INTO t VALUES (1, CAST(REPEAT('AA', 8000) AS BIT VARYING));
SET SYSTEM PARAMETERS 'fault_injection_ids=700007; fault_injection_fire_at_occurrence=1';
INSERT INTO t VALUES (2, CAST(REPEAT('BB', 20000) AS BIT VARYING));
SELECT COUNT(*) FROM t;
