CREATE TABLE t03 (id VARCHAR(4000), payload BIT VARYING STORAGE FORCE_OUTLINE) PARTITION BY RANGE(CHAR_LENGTH(id)) (PARTITION p0 VALUES LESS THAN(3000), PARTITION p1 VALUES LESS THAN MAXVALUE);
INSERT INTO t03 VALUES(REPEAT('a',2999),REPEAT(X'AA',64));
UPDATE t03 SET payload=REPEAT(X'BB',64);
UPDATE t03 SET id=REPEAT('b',3000);
SELECT COUNT(*) FROM t03__p__p1 WHERE id=REPEAT('b',3000) AND payload=CAST(REPEAT(X'BB',64) AS BIT VARYING);
SHOW HEAP OOS OF t03__p__p1;
ROLLBACK;
