[service]
service=server
[common]
cubrid_port_id=1523
data_buffer_size=256M
log_buffer_size=64M
max_clients=20
enable_string_compression=no
vacuum_worker_count=1
vacuum_master_interval_in_msecs=10
stored_procedure=no
